const REGISTER="user:REGISTER"
const LOGIN="user:LOGIN"
const GET_ALL_USERS="user:GET_ALL_USERS"
const GET_USER_BY_ID="user:GET_USER_BY_ID"
const UPDATE_USER="user:UPDATE_USER"
const DELETE_USER="user:DELETE_USER"
const UPLOAD_USER_IMAGE = "user:UPLOAD_USER_IMAGE";
const DELETE_USER_IMAGE = "user:DELETE_USER_IMAGE";
const RESET_PASSWORD = "user:RESET_PASSWORD";
const GET_CART_BY_USER_ID="user:GET_CART_BY_USER_ID"


const CREATE_PRODUCT="product:CREATE_PRODUCT"
const GET_ALL_PRODUCTS="product:GET_ALL_PRODUCTS"
const GET_PRODUCT_BY_ID="product:GET_PRODUCT_BY_ID"
const UPDATE_PRODUCT="product:UPDATE_PRODUCT"
const DELETE_PRODUCT="product:DELETE_PRODUCT"
const UPLOAD_IMAGE="product:UPLOAD_IMAGE"
const ADD_IMAGES_TO_ARRAY="product:ADD_IMAGES_TO_ARRAY"
const DELETE_IMAGE="product:DELETE_IMAGE"
const REMOVE_IMAGES_FROM_ARRAY="product:REMOVE_IMAGES_FROM_ARRAY"





const ADD_ITEM="cart:ADD_ITEM"
const UPDATE_CART="cart:UPDATE_CART"
const GET_CART="cart:GET_CART"
const GET_ALL_ITEMS="cart:GET_ALL_ITEMS"
const DELETE_ITEM="cart:DELETE_ITEM"
const FLUSH="cart:FLUSH"




const CHECK_OUT_ORDER="order:CHECK_OUT_ORDER"
const GET_ALL_ORDERS="order:GET_ALL_ORDERS"
const GET_ORDER_BY_ID="order:GET_ORDER_BY_ID"
const UPDATE_ORDER="order:UPDATE_ORDER"
const CANCEL_ORDER="order:CANCEL_ORDER"






const CREATE_REVIEW="review:CREATE_REVIEW"
const GET_ALL_REVIEWS="review:GET_ALL_REVIEWS"
const GET_REVIEW_BY_ID="review:GET_REVIEW_BY_ID"
const UPDATE_REVIEW="review:UPDATE_REVIEW"
const DELETE_REVIEW="review:DELETE_REVIEW"




const ADD_PRODUCT_TO_WISHLIST="wishlist:ADD_PRODUCT_TO_WISHLIST"
const GET_ALL_WISHLISTS="wishlist:GET_ALL_WISHLISTS"
const GET_WISHLIST_BY_ID="wishlist:GET_WISHLIST_BY_ID"
const REMOVE_PRODUCT_FROM_WISHLIST="wishlist:REMOVE_PRODUCT_FROM_WISHLIST"


module.exports={
    REGISTER,
    LOGIN,
    GET_ALL_USERS,
    GET_USER_BY_ID,
    UPDATE_USER,
    DELETE_USER,
    UPLOAD_USER_IMAGE,
    DELETE_USER_IMAGE,
    RESET_PASSWORD,
    GET_CART_BY_USER_ID,

     ADD_ITEM,
     UPDATE_CART,
     GET_CART,
     GET_ALL_ITEMS,
     DELETE_ITEM,
     FLUSH,


    CREATE_PRODUCT,
    GET_ALL_PRODUCTS,
    GET_PRODUCT_BY_ID,
    UPDATE_PRODUCT,
    DELETE_PRODUCT,
    UPLOAD_IMAGE,
    ADD_IMAGES_TO_ARRAY,
    DELETE_IMAGE,
    REMOVE_IMAGES_FROM_ARRAY,

    CHECK_OUT_ORDER,
    GET_ALL_ORDERS,
    GET_ORDER_BY_ID,
    UPDATE_ORDER,
    CANCEL_ORDER,

    CREATE_REVIEW,
    GET_ALL_REVIEWS,
    GET_REVIEW_BY_ID,
    UPDATE_REVIEW,
    DELETE_REVIEW,

   ADD_PRODUCT_TO_WISHLIST,
   GET_ALL_WISHLISTS,
   GET_WISHLIST_BY_ID,
   REMOVE_PRODUCT_FROM_WISHLIST,

}