let app=require("express").Router()

let userRoutes=require("./users/user.route")
let uploadUserRoutes=require("./users/upload.route")
let exportUserRoutes=require("./users/export.route")
let reviewRoutes=require("./reviews/review.route")
let exportReviewRoutes=require("./reviews/export.route")
let orderRoutes=require("./order/order.route")
let exportOrderRoutes=require("./order/export.route")
let productRoutes=require("./product/product.route")
let uploadProductRoutes=require("./product/upload.route")
let exportProductRoutes=require("./product/export.route")
let wishlistRoutes=require("./wishlist/wishlist.route")
let exportWishlistRoutes=require("./wishlist/export.route")
let cartRoutes=require("./cart/cart.route")
let exportCartRoutes=require("./cart/export.route")


app.use(userRoutes)
app.use(uploadUserRoutes)
app.use(exportUserRoutes)
app.use(reviewRoutes)
app.use(exportReviewRoutes)
app.use(orderRoutes)
app.use(exportOrderRoutes)
app.use(productRoutes)
app.use(uploadProductRoutes)
app.use(exportProductRoutes)
app.use(wishlistRoutes)
app.use(exportWishlistRoutes)
app.use(cartRoutes)
app.use(exportCartRoutes)

module.exports=app